image: python:3.9

stages:
  - build
  - test
  - deploy

before_script:
  - python3 -m pip install --upgrade pip setuptools wheel

build:
  stage: build
  script:
    - python3 setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*

test:
  stage: test
  script:
    - python3 -m pip install pytest
    - python3 -m pytest

deploy:
  stage: deploy
  script:
    - python3 -m pip install twine
    - python3 -m twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD --verbose --skip-existing dist/*
  environment:
    name: production

  only:
    - main # Only run the deploy job for the master branch
